name: pixel-battle

services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
    container_name: pixel-battle-backend
    volumes:
      - ../..:/pixel-battle
    networks:
      - private-network
    ports:
      - 8000:8000
    depends_on:
      - redis1
      - redis2
      - redis3
    environment:
      WATCHFILES_FORCE_POLLING: true
      CANVAS_REDIS_CLUSTER_URL: redis://redis1:6379/0
      CANVAS_METADATA_REDIS_CLUSTER_URL: redis://redis1:6379/0
      JWT_SECRET: super-secret-secret
    command: python src/pixel_battle/deployment/god_service

  redis1:
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
    container_name: pixel-battle-redis1
    volumes:
      - redis1-db:/data
      - ./redis:/mnt
    networks:
      - private-network
    depends_on:
      - redis2
      - redis3
    command: ash /mnt/scripts/start-cluster-creation-node.sh

  redis2:
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
    container_name: pixel-battle-redis2
    volumes:
      - redis2-db:/data
      - ./redis:/mnt
    networks:
      - private-network

  redis3:
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
    container_name: pixel-battle-redis3
    volumes:
      - redis3-db:/data
      - ./redis:/mnt
    networks:
      - private-network

volumes:
  redis1-db: null
  redis2-db: null
  redis3-db: null

networks:
  private-network:
    driver: bridge
