name: pixel-battle

services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
    container_name: pixel-battle-backend
    volumes:
      - ../..:/pixel-battle
      - backend-venv:/run/poetry
    networks:
      - private-network
    ports:
      - 8000:8000
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
    environment:
      CANVAS_REDIS_CLUSTER_URL: redis://redis1:6379/0
      CANVAS_METADATA_REDIS_CLUSTER_URL: redis://redis1:6379/0
      JWT_SECRET: super-secret-secret
      ADMIN_KEY: super-secret-admin-key
    labels:
      pixel-battle: true
    command: python src/pixel_battle/deployment/god_service

  redis1:
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
    container_name: pixel-battle-redis1
    volumes:
      - redis1-db:/data
      - ./redis:/mnt
    networks:
      - private-network
    labels:
      pixel-battle: true
    depends_on:
      redis2:
        condition: service_healthy
        restart: true
      redis3:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ash /mnt/scripts/is-cluster-ok.sh
      start_interval: 0s
      interval: 1s
      retries: 30
    command: ash /mnt/scripts/start-cluster-creation-node.sh

  redis2:
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
    container_name: pixel-battle-redis2
    volumes:
      - redis2-db:/data
      - ./redis:/mnt
    networks:
      - private-network
    labels:
      pixel-battle: true

  redis3:
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
    container_name: pixel-battle-redis3
    volumes:
      - redis3-db:/data
      - ./redis:/mnt
    networks:
      - private-network
    labels:
      pixel-battle: true

volumes:
  redis1-db:
    labels:
      pixel-battle: true
  redis2-db:
    labels:
      pixel-battle: true
  redis3-db:
    labels:
      pixel-battle: true
  backend-venv:
    labels:
      pixel-battle: true

networks:
  private-network:
    driver: bridge
