name: pixel-battle

services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/dev/backend/Dockerfile
      tags:
        - "pixel-battle-backend:dev"
    container_name: pixel-battle-backend
    volumes:
      - ../..:/pixel-battle
      - backend-data:/run/pixel-battle
    networks:
      - private-network
    ports:
      - 8000:8000
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
    environment:
      CANVAS_REDIS_CLUSTER_URL: redis://redis1:6379/0
      CANVAS_METADATA_REDIS_CLUSTER_URL: redis://redis1:6379/0
      JWT_SECRET: super-secret-jwt-secret
      ADMIN_KEY: super-secret-admin-key
      CHUNK_REFREH_TASK_PUSHING_INTERVAL_SECONDS: 8
    labels:
      pixel-battle: true
    cpus: 0.5
    command: god-service

  redis1:
    image: pixel-battle-redis:dev
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
      tags:
        - "pixel-battle-redis:dev"
    container_name: pixel-battle-redis1
    volumes:
      - redis1-data:/data
      - ./redis:/mnt
    networks:
      - private-network
    labels:
      pixel-battle: true
    depends_on:
      redis2:
        condition: service_healthy
        restart: true
      redis3:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ash /mnt/scripts/is-cluster-ok.sh
      interval: 1s
    command: ash /mnt/scripts/start-cluster-creation-node.sh

  redis2:
    image: pixel-battle-redis:dev
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
      tags:
        - "pixel-battle-redis:dev"
    container_name: pixel-battle-redis2
    volumes:
      - redis2-data:/data
      - ./redis:/mnt
    networks:
      - private-network
    labels:
      pixel-battle: true

  redis3:
    image: pixel-battle-redis:dev
    build:
      context: ../../
      dockerfile: deployments/dev/redis/Dockerfile
      tags:
        - "pixel-battle-redis:dev"
    container_name: pixel-battle-redis3
    volumes:
      - redis3-data:/data
      - ./redis:/mnt
    networks:
      - private-network
    labels:
      pixel-battle: true

volumes:
  backend-data:
    labels:
      pixel-battle: true
  redis1-data:
    labels:
      pixel-battle: true
      db: true
  redis2-data:
    labels:
      pixel-battle: true
      db: true
  redis3-data:
    labels:
      pixel-battle: true
      db: true

networks:
  private-network:
    driver: bridge
