name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  redeploy:
    runs-on: self-hosted
    environment: Production
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: redeploy
        run: bash deployments/prod/redeploy.sh ${{ vars.REDEPLOY_OPTIONS }}
        env:
          ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DOMAIN_EMAIL: ${{ secrets.DOMAIN_EMAIL }}
          DOMAIN: ${{ vars.DOMAIN }}
