name: pixel-battle

services:
  https-server:
    image: pixel-battle-https-server:prod
    build:
      context: ../../
      dockerfile: deployments/prod/https-server/Dockerfile
      tags:
        - "pixel-battle-https-server:prod"

    container_name: pixel-battle-https-server
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 443:443
    healthcheck:
      test: wget https://${DOMAIN}/api/0.1.0v/healthcheck -q -O /dev/null
      start_period: 1m
      start_interval: 2s
      interval: 10s
    networks:
      - backend-net
    mem_limit: 10mb
    environment:
      DOMAIN: ${DOMAIN}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx

  backend:
    image: pixel-battle-backend:prod
    build:
      context: ../../
      dockerfile: deployments/prod/backend/Dockerfile
      tags:
        - "pixel-battle-backend:prod"

    container_name: pixel-battle-backend
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
    environment:
      CANVAS_REDIS_CLUSTER_URL: redis://redis1:6379/0
      CANVAS_METADATA_REDIS_CLUSTER_URL: redis://redis1:6379/0
      CHUNK_REFREH_TASK_PUSHING_INTERVAL_SECONDS: 60
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_KEY: ${ADMIN_KEY}
    command:
      uvicorn pixel_battle.deployment.god_service.asgi:app --host 0.0.0.0
    mem_limit: 105mb
    healthcheck:
      test: wget backend:8000/api/0.1.0v/healthcheck -q -O /dev/null
      start_period: 10m
      start_interval: 2s
      interval: 10s
    networks:
      - backend-net
      - redis-cluster-net

  redis1:
    image: pixel-battle-reids:prod
    build:
      context: ../../
      dockerfile: deployments/prod/redis/Dockerfile
      tags:
        - "pixel-battle-reids:prod"

    container_name: pixel-battle-redis1
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
      redis: true
      db: true
    volumes:
      - redis1-data:/data
    command: redis-server /mnt/redis.conf
    mem_limit: 30mb
    healthcheck:
      test: echo PING | redis-cli | grep -qF PONG
      start_period: 1m
      start_interval: 1s
      interval: 2s
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.150.11

  redis2:
    image: pixel-battle-reids:prod
    build:
      context: ../../
      dockerfile: deployments/prod/redis/Dockerfile
      tags:
        - "pixel-battle-reids:prod"

    container_name: pixel-battle-redis2
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
      redis: true
      db: true
    volumes:
      - redis2-data:/data
    command: redis-server /mnt/redis.conf
    mem_limit: 30mb
    healthcheck:
      test: echo PING | redis-cli | grep -qF PONG
      start_period: 1m
      start_interval: 1s
      interval: 2s
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.150.12

  redis3:
    image: pixel-battle-reids:prod
    build:
      context: ../../
      dockerfile: deployments/prod/redis/Dockerfile
      tags:
        - "pixel-battle-reids:prod"

    container_name: pixel-battle-redis3
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
      redis: true
      db: true
    volumes:
      - redis3-data:/data
    command: redis-server /mnt/redis.conf
    mem_limit: 30mb
    healthcheck:
      test: echo PING | redis-cli | grep -qF PONG
      start_period: 1m
      start_interval: 1s
      interval: 2s
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.150.13

networks:
  backend-net:
    driver: bridge

  redis-cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.150.0/24"

volumes:
  redis1-data:
    labels:
      pixel-battle: true
      deployment: prod
      db: true

  redis2-data:
    labels:
      pixel-battle: true
      deployment: prod
      db: true

  redis3-data:
    labels:
      pixel-battle: true
      deployment: prod
      db: true
