name: pixel-battle

services:
  https-server:
    image: nginx:1.27-alpine3.21-perl
    container_name: pixel-battle-https-server
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ssl-data:/mnt/ssl
    depends_on:
      backend:
        condition: service_healthy
      certbot:
        condition: service_healthy
    ports:
      - 443:443
    healthcheck:
      test: wget https-server/api/0.1.0v/healthcheck -q -O /dev/null
      start_period: 10m
      start_interval: 10s
      interval: 1h
      #cpus: 0.025
      #mem_limit: 10mb

  http-server:
    container_name: pixel-battle-http-server
    image: nginx:1.27-alpine3.21-perl
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
    volumes:
      - ./domain-defence/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    healthcheck:
      test: wget http-server/healthcheck -q -O /dev/null
      start_period: 1m
      start_interval: 1s
      interval: 1h
    #cpus: 0.025
    #mem_limit: 5mb

  certbot:
    container_name: pixel-battle-certbot
    build:
      context: ../../
      dockerfile: deployments/prod/certbot/Dockerfile
      tags:
        - "pixel-battle-certbot:prod"
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
    volumes:
      - ssl-data:/mnt/ssl
    depends_on:
      http-server:
        condition: service_healthy
    environment:
      DOMAIN: ${DOMAIN}
      DOMAIN_EMAIL: ${DOMAIN_EMAIL}
    # cpus: 0.5
    # mem_limit: 100mb

  backend:
    container_name: pixel-battle-backend
    build:
      context: ../../
      dockerfile: deployments/prod/backend/Dockerfile
      tags:
        - "pixel-battle-backend:prod"
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
    environment:
      CANVAS_REDIS_CLUSTER_URL: redis://redis1:6379/0
      CANVAS_METADATA_REDIS_CLUSTER_URL: redis://redis1:6379/0
      CHUNK_REFREH_TASK_PUSHING_INTERVAL_SECONDS: 60
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_KEY: ${ADMIN_KEY}
    command:
      uvicorn pixel_battle.deployment.god_service.asgi:app --host 0.0.0.0
    # cpus: 0.2
    #mem_limit: 105mb
    healthcheck:
      test: wget backend:8000/api/0.1.0v/healthcheck -q -O /dev/null
      start_period: 10m
      start_interval: 10s
      interval: 1h

  redis1:
    image: redis:7.4.1-alpine3.20
    container_name: pixel-battle-redis1
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
      redis: true
      db: true
    volumes:
      - ./redis:/mnt
      - redis1-data:/data
    command: redis-server /mnt/redis.conf
    #cpus: 0.05
    #mem_limit: 30mb
    healthcheck:
      test: echo PING | redis-cli | grep -qF PONG
      start_period: 1m
      start_interval: 1s
      interval: 1m

  redis2:
    image: redis:7.4.1-alpine3.20
    container_name: pixel-battle-redis2
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
      redis: true
      db: true
    volumes:
      - ./redis:/mnt
      - redis2-data:/data
    command: redis-server /mnt/redis.conf
    #cpus: 0.05
    #mem_limit: 30mb
    healthcheck:
      test: echo PING | redis-cli | grep -qF PONG
      start_period: 1m
      start_interval: 1s
      interval: 1m

  redis3:
    image: redis:7.4.1-alpine3.20
    container_name: pixel-battle-redis3
    restart: always
    labels:
      pixel-battle: true
      deployment: prod
      redis: true
      db: true
    volumes:
      - ./redis:/mnt
      - redis3-data:/data
    command: redis-server /mnt/redis.conf
    #cpus: 0.05
    #mem_limit: 30mb
    healthcheck:
      test: echo PING | redis-cli | grep -qF PONG
      start_period: 1m
      start_interval: 1s
      interval: 1m

volumes:
  ssl-data:
    labels:
      pixel-battle: true
      deployment: prod
  redis1-data:
    labels:
      pixel-battle: true
      deployment: prod
      db: true
  redis2-data:
    labels:
      pixel-battle: true
      deployment: prod
      db: true
  redis3-data:
    labels:
      pixel-battle: true
      deployment: prod
      db: true
